Initial Iroha2 Swift library with schema builder and generated code
hyperledger/iroha-ios pull request #130
Opened 2021-07-14 16:04 UTC by posplaw

Removed Iroha v1 code
Added IrohaSwiftSchemaBuilder project which builds Swift files from Iroha v2 JSON schema
Added IrohaSwiftScale project which contains types required by SCALE, and implementation for Swift Coding to Encode/Decode SCALE types, available as separate Pod
Storing pre-generated schema from latest Iroha v2 schema export
Added utility scripts to generate schema, inject into dev pod or .xcodeproj

Signed-off-by: Alex Oakley <oakley@soramitsu.co.jp>
Closes #128

2021-07-16 21:06 UTC, ERussel commented on IrohaSwiftScale/Classes/ScaleCoding/Decoder/ScaleSingleValueDecodingContainer.swift
> +        (((try? dataReader.read(1, at: codingPath).first.map { $0 == 0b0 }) as Bool??)) == true
I think it might be a problem here when when one try parse inconsistent because out of bound is silenced here.

2021-07-16 21:09 UTC, ERussel commented on IrohaSwiftScale/Classes/ScaleCoding/Encoder/ScaleEncoder+Custom.swift
> +private enum ScaleBool: Int, Encodable {
Looks like it should be UInt8 otherwise we are writing 8 bytes. Could confirm with the following test:
```
func testConcreateBool() throws {
        let testCases: [(Bool?, Data)] = [
            (nil, Data([0])),
            (false, Data([1])),
            (true, Data([2]))
        ]

        for testCase in testCases {
            let actualData = try ScaleEncoder().encode(testCase.0)
            XCTAssertEqual(actualData, testCase.1)
        }
    }
```

2021-07-16 21:12 UTC, ERussel commented on IrohaSwiftScale/Classes/ScaleCoding/Decoder/ScaleDecoder+Custom.swift
> +private enum ScaleBool: Int, Decodable {
What is the point to duplicate enum for Encoder/Decoder?

2021-07-16 21:18 UTC, ERussel commented on IrohaSwiftScale/Classes/Extras/Compact.swift
> +            let data = withUnsafeBytes(of: value.value.upperBits) { Data($0) } + withUnsafeBytes(of: value.value.lowerBits) { Data($0) }
I think there is a problem here because always 16 bytes is written no matter what is the value and how many bytes it fits. Could confirm with the following test:
```
func testConcreateCompact() throws {
        let testCases: [(Compact<UInt128>, Data)] = [
            (Compact(0), Data([0])),
            (Compact(1), Data([4])),
            (Compact(63), Data([252])),
            (Compact(64), Data([1, 1])),
            (Compact(255), Data([253, 3])),
            (Compact(511), Data([253, 7])),
            (Compact(16383), Data([253, 255])),
            (Compact(16384), Data([2, 0, 1, 0])),
            (Compact(65535), Data([254, 255, 3, 0])),
            (Compact(1073741823), Data([254, 255, 255, 255])),
            (Compact(1073741824), Data([3, 0, 0, 0, 64]))
        ]

        for testCase in testCases {
            let actualData = try ScaleEncoder().encode(testCase.0)
            XCTAssertEqual(actualData, testCase.1)
        }
    }
```

2021-07-16 21:23 UTC, ERussel requested changes
Generally I liked the idea of SCALE coding implementation using native Encoder/Decoder protocols. It took more to develop but in the end a user just needs to define a structure without manually implementing boilerplate code for serialisation. However bugs should be fixed.

Also I suggest to use test vectors in tests other than just using encoding/decoding approach because it doesn't protect from the related error both in encoder and decoder.

2021-09-12 18:59 UTC, ERussel commented on IrohaSwiftSDK/Classes/API/IrohaAccount.swift
> +    public var publicKey: [UInt8]
I think it should be let because of dependency between values we always change both.

2021-09-12 20:14 UTC, ERussel approved these changes
Let's merge this one and try to improve in smaller PRs.

The following improvements should be considered:
1) Research web sockets to proper handle multiple messages
2) Consider creating a builder to construct instructions because currently a client should create them manually and pass as list to IrohaClient.
3) Consider ping/pong implementation for web sockets.

2021-09-12 20:14 UTC, ERussel commented on IrohaSwiftSchemaBuilder/IrohaSwiftSchemaBuilder/Sources/FileManager.swift
> +    func readFile(path: String) -> [String: Any]? {
Probably leave it throwable because from the error a dev can understand concrete parsing problems

2021-09-12 20:14 UTC, ERussel commented on IrohaSwiftSchemaBuilder/IrohaSwiftSchemaBuilder/Sources/FileManager.swift
> +        let directory = "/" + path.split(separator: "/").dropLast().joined(separator: "/")
I think String has `pathComponents` function, so `split` is overhead

2021-09-13 16:20 UTC, posplaw commented on IrohaSwiftSDK/Classes/API/Queries/SubmitQuery.swift
> +    let statusCodeToErrors = [500: Error.queryRejected]
This is special error mentioned @ https://github.com/hyperledger/iroha/blob/iroha2-dev/docs/source/references/api_spec.md

2021-09-14 16:05 UTC, merged